name = "impulse_app"
type = "webpack"
zone_id = "94c4970ecc9c1585611b6a848813ef46"
account_id = "e6da38c5a4e61a7bbb5a7e8083313256"
usage_model = ""
compatibility_flags = []
workers_dev = true
site = { bucket = "build", entry-point = "workers-site" }
compatibility_date = "2022-01-20"

[env.prod]
route = "app.askimpulse.com/*"

[env.beta]
route = "beta-app.askimpulse.com/*"

[env.dev]
route = "dev-app.askimpulse.com/*"
